version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - $PATH_TO_PHP_PROJECT:/var/www/html/project
      - $PATH_TO_PHPMYADMIN:/var/www/html/phpmyadmin
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - $PATH_TO_PHP_PROJECT:/var/www/html/project
      - $PATH_TO_PHPMYADMIN:/var/www/html/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - PMA_HOST=mysql
      - PMA_PORT=3306      
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
networks:
  frontend:
  backend: